### ISSUE TITLE
Feature: Order Form Profiles

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#104]
Allow the user to save a populated order form for later restoration. Very useful in testing when having to enter the same details over and over again, but it has also been requested multiple times by multiple users.

Should grab & save all field state into a 'profile' or so

### TODO
* [ ] create profile save system
* [ ] add profile dropdown to OF, that causes profile values to fill in
* [ ] allow setting of default profiles (i.e. user often uses the same amount in orders on a market, etc)
