### ISSUE TITLE
Feature: Hotkeys

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#105]
Low priority but requested by several people; we need a hotkey system for order execution and app navigation. This should be configurable by the user.

### TODO
* [ ] design hotkey list (non-trivial, check MT4/etc for ideas)
* [ ] implement hotkey system
* [ ] implement hotkey edit UI
