### ISSUE TITLE
Feature: Low Level Trading Limits

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#106]
The very first version of `bfx-hf-algo` had this, but was rewritten and support for it was dropped in the process. Would be very useful to have again.

The user should be able to set at least the following limits:
- max trade size
- max position size (?)
- max traded per X minutes (research interval?)
- max traded per day
- and/or more!

### TODO
* [ ] implement limit system in `bfx-hf-algo`
* [ ] design UI for limits
  - limit specification (add to user settings page?)
  - limit usage info if in interval
* [ ] design limit exceeded behavior (stop AOs, show dialogue/notification, etc)
* [ ] hook up limit UI
