### ISSUE TITLE
Feature: Strategy Execution

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#109]
This includes both the UI side (multiple pages) and `bfx-hf-server` internal updates.

### TODO
* [ ] create strategy system https://github.com/bitfinexcom/bfx-hf-server/issues/14
* [ ] design strategy UI
* [ ] implement strategy UI
