### ISSUE TITLE
Feature: VPS Auto-Deployment

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#110]
This has been planned for ages, and is not too difficult, just low priority. We need to add an UI allowing the user to provision a VPS (given the necessary API key/secret) and deploy an instance of `bfx-hf-algo-server` on it with a systemd service file (enabled and started).

Includes Bitfinex hosting!

### TODO
* [ ] create provisioning system
* [ ] create bfx hosting logic
* [ ] create linode logic
* [ ] create digitalocean logic
* [ ] create AWS logic
* [ ] create GCP logic
* [ ] refactor `bfx-hf-server` to use remote instance, and kill local one
  * [ ] resume to remote instance if configured on last run
* [ ] design UI
  * [ ] decide server metrics reporting (uptime, load, etc, maybe 'update packages' button)
* [ ] implement UI
* [ ] update app UI/UX to notify the user when using a remote server for algos (banner or in status bar)
