### ISSUE TITLE
Feature: Expose DMS setting

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#113]
Expose the bitfinex exchange connection DMS flag as a user setting.

### TODO
* [x] create user setting field
* [ ] set DMS based on value
* [ ] verify algos are not adversely affected (they will be, in strange ways)
* [ ] refactor algos where necessary for painless no-DMS
