### ISSUE TITLE
Refactor: Merge Icon Fonts

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#114]
Currently `bfx-hf-chart` uses its own icons; I've asked Genc to package a merged font, we will host it as a library: `bfx-hf-ui-fonts`

### TODO
* [ ] acquire `bfx-hf-ui-fonts`
* [ ] create/deploy `bfx-hf-ui-fonts` repo
* [ ] update font names if/where necessary
