### ISSUE TITLE
Refactor: Decrease Build Size

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#115]
As of the time of issue creation, a built main file is `1.25 MB` after gzip! This is mainly due to `bfx-hf-server` which pulls in tons of backend dependencies, like mime type definitions.

![Screenshot from 2020-01-25 09 25 23](https://user-images.githubusercontent.com/1319812/73115117-a2d6a480-3f54-11ea-9e33-df86c222bb91.png)

### TODO
* [ ] run webpack bundle analyzer and post initial results here for later comparison
* [ ] optimize!
* [ ] run analyzer again and compare
* [ ] decrease build size as much as possible
