### ISSUE TITLE
Refactor: axios usage

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#44]
Currently `axios` is used to pull the latest version info from the Github repo in order to render the version & upgrade button in the `StatusBar` component here: https://github.com/bitfinexcom/bfx-hf-ui/blob/20e311adc023ed171cd57de5fe532cb3e4f76190/src/components/StatusBar/StatusBar.js#L95

This needs to be refactored into the redux system, so we don't make the GET request on every render of `StatusBar` (not very efficient).

### TODO
* [ ] Add/use existing reducer for data (I recommend `meta`)
* [ ] Add a saga to fetch the current version & run it on startup, potentially on an interval (something large, maybe 60 minutes, not sure)
* [ ] Add a selector to access the remote version value
* [ ] Use the selector in `StatusBar.container` to pass the value as a prop
* [ ] Refactor `StatusBar` to use the prop.

Likely fixed by https://github.com/bitfinexcom/bfx-hf-ui/pull/45 but needs review
