### ISSUE TITLE
Feature: Integrate HF affiliate code

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#82]
### TODO
* [ ] user settings page & persistence
* [ ] update bfx adapter to accept and use aff code
* [ ] pass aff code to bfx adapter
