### ISSUE TITLE
Feature: Offline Mode

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#84]
When offline we should theoretically be able to view historical candle data, as it is synced locally. However the app fails to start initially due to being unable to fetch market meta data.

### TODO
* [ ] safely fail to fetch exchange metadata at startup, don't exit
* [ ] disable unnecessary networked services (ex pool, algo server, etc)
* [ ] display offline notice to user
* [ ] display 'go online' button, triggering full server restart.
