### ISSUE TITLE
Feature: Theme System

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#94]
We need to refactor all component css to export colors/fonts/etc into an own theme, for easier customization in the future.

As we have a complete redesign coming up next month, the system needs to be flexible enough to accommodate it.

### TODO
* [x] architect system/decide on lib
* [ ] update all components, use current styles as `classic-dark` theme
* [ ] make `classic-light` example theme
