### ISSUE TITLE
Feature: Plugin System

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#99]
Currently the HF has a plugin system in the form of `bfx-hf-models` adapters, which abstract Trade and Candle sync logic. There is however a secondary system used within `bfx-hf-server` which cannot be easily removed (individual exchange connection classes).

As a note, `bfx-hf-server` relies on the `bfx-hf-models` adapters for all algo order execution and trade/candle syncing, not the internal exchange connection classes.

### TODO
  * [ ] decide on plugin architecture
    - technically half of a plugin is in `bfx-hf-server` and half in `bfx-hf-ext-plugin-EXCHANGE`
  * [ ] refactor existing plugins if needed
  * [ ] design plugin UI
  * [ ] implement plugin system
